###CADASTRAR NOVO PRODUTO
POST  http://localhost:5006/api/produto/cadastrar
Content-Type: application/json

//NO CASO DO STATUS EU N VOU CRIAR O PRODUTO(TAREFA) JA COM O STATUS PRONTO OU SLA< SEMPRE VAI INICIAR COMO STATUS PENDENTE
//DPS EU FAÇO PRA QUE QUANDO EU ALTERAR (PUT) O PRODUTO(TAREFA) EU DIGA O NOVO STATUS

{   "Nome": "Porsche 718",
    "Descricao":"Carro esportivo",
    "Valor": 1000000,
    "Status": "Alto"
    
}

###LISTAR TODOS OS PRODUTOS
GET  http://localhost:5006/api/produto/listarTudo

###BUSCAR UM PRODUTO
GET  http://localhost:5006/api/produto/buscar/id:1

###DELETAR UM PRODUTO
DELETE  http://localhost:5006/api/produto/deletar/id:20

###ATUALIZAR UM PRODUTO
PUT   http://localhost:5006/api/produto/alterar/id:21
Content-Type: application/json

{
    "Nome": "Porsche Cayenne",
    "Descricao": "SUV de luxo",
    "Valor": 500000
}

###SCORE BAIXO
GET  http://localhost:5006/api/produto/scorebaixo

###SCORE ALTO
GET  http://localhost:5006/api/produto/scorealto